name: Add Mask
on: push

jobs:
    log:
        runs-on: ubuntu-latest
        env:
            PASSWORD: "secret"
        steps:
            - run: echo "::add-mask::${{env.PASSWORD}}"
            - run: echo "${{env.PASSWORD}}"
