name: Annotation
on: push

jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: echo "::warning::This is a warning"
            - run: echo "::error::This is an error"
            - run: echo "::notice::This is a notice"
            - run: echo "::debug::This is a debug"
