name: Choice

on:
  workflow_dispatch:
    inputs:
        log-level:
            type: choice
            options:
                - info
                - debug
                - warn

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "&{{inputs.log-level}}"
