name: Manual

env:
    BRANCH: "env test" # 環境変数の追加
on:
  workflow_dispatch:
    inputs:
        greeting:
            type: string
            default: "Hello"
            required: true
            description: "Greeting to print"



jobs:
  hello:
    runs-on: ubuntu-latest
    env:
        ACTOR: ${{github.actor}}
        USERNAME: ${{vars.USERNAME}}
    steps:
      - run: echo "${{ env.ACTOR }}"
      - run: echo "${{ env.USERNAME }}"
