name: Parallel Jobs
on: push

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "First job finished"
    second:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "Second job finished"

    third:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "Third job finished"
